from django.urls import path
from . import views
from django.conf import settings
# from django.conf.urls.static import static
#create a list of url patterns
urlpatterns = [
    path('', views.Home, name='home'),
    path('about/', views.About, name='about'),
    path('services/', views.Services, name='Services'),
    path('assigned_patients/', views.assigned_patients, name='assigned_patients'),
    path('departments/', views.Departments, name='Departments'),
    path('Admin/', views.Admin, name='Admin'),
    path('Admin_patient/', views.AdminPatient, name='Admin_patient'),
    path('Admin_Table/', views.Admin_Table, name='Admin_Table'),
    path('Staff/', views.Staff, name='Staff'),
    path('Doctors/', views.DoctorsPage, name='Doctors'),
    path('BookingList/', views.BookingList, name="BookingList"),
    path('DoctorsList/', views.DoctorsList, name='DoctorsList'),
    path('AllDoctors/', views.AllDoctors, name='AllDoctors'),
    path('AvailableDoctors/', views.AvailableDoctors, name='AvailableDoctors'),
    path('Booking/', views.BookingView, name='Booking'),
    path('Register/', views.RegisterPatients, name="Register"),
    path('Login/', views.Login, name="Login"),
    path('approved_patients/', views.DoctorApprovePatients, name='approved_patients'),
    path('AllocatedPatients/', views.approve_booking, name='AllocatedPatients'),
    path('DoctorPatient/', views.DoctorAssignedPatients, name='DoctorPatient'),
    path('Booking_Appoint/', views.BookingAppointment, name='Booking_Appoint'),
    path('Register_Doctor/', views.register_doctor, name= "Register_Doctor"),
    path('BookingViewAppointment/', views.BookingViewAppointment, name='BookingViewAppointment'),
    path('BookingTable/', views.BookingTable, name="BookingTable"),
    path('BookingView/', views.BookingViewAppointment, name='BookingView'),
    path('Adminview/', views.Adminview, name='Adminview'),
    path('review_patient/', views.review_patient_view, name='review_patient'),
    path('doctor_management/', views.doctor_management, name='doctor_management'),
    path('AdminApproval/', views.Admin_Approve, name='AdminApproval'),
    path('AdminDoctors/', views.AdminDoctors, name='AdminDoctors'),
    path('ApproveDoctor/', views.ApproveByDoctor, name='ApproveDoctor'),
    path('Admin_Approved/',  views.Admin_Approved, name="Admin_Approved"),
    path("DoctorsLogin/", views.doctor_login, name="doctor_login"),
    path('DoctorsApproval/',views.DoctorApprovePatients, name='DoctorsApproval'),
    path('PatientDashboard/', views.PatientDashboard, name="PatientDashboard"),
    path('PatientRecords/', views.DoctorsPatientRecords, name='PatientRecords'),
    path('DoctorDashboard/', views.DoctorsDashboard, name='DoctorDashboard'),
    path('approve-booking/<int:booking_id>/', views.approve_booking, name='approve_booking'),
    path('doctors_registration/', views.doctors_registration, name='doctors_registration'),
    path('Main_Doctors/', views.Main_Doctors, name='Main_Doctors'),
    path('AdminBash/',views.DashboardAdmin, name='AdminBash'),
    path('admin_patient_dashboard/', views.admin_patient_dashboard, name='admin_patient_dashboard'),
    path('book_appointment/', views.book_appointment, name='book_appointment'),
    path('admin_pending/', views.admin_pending, name='admin_pending'),
    path('Admin_Appointments/', views.Admin_Appointments, name='Admin_Appointments'),
    path('approve/<int:booking_id>/', views.approve_booking, name='approve_booking'),
    # path('Pharmacy/', views.Pharmacy, name='Pharmacy'),
    path('manage_appointments/', views.manage_appointments, name='manage_appointments'),
    path('admin_approve1/<int:booking_id>/', views.approve_booking1, name='admin_approve1'),
    path('admin_reject1/<int:booking_id>/', views.reject_booking1, name='admin_reject1'),
    path('Allocated/', views.assigned_patients, name='Allocated'),
    path('Doctor_patient/', views.Doctor_patients, name='Doctor_patient'),
    path('approve_booking/', views.approve_booking, name='approve_booking'), 
    path('patients/', views.AdminPatientView, name='patient'),
    path('allocate_doctor/', views.Doctor_Availability, name='allocate_doctor'),
    path('patient_record/', views.PatientRecord, name='patient_record'),
    path('approve/<int:id>/', views.ApproveByDoctor , name='approvalAppointment'),
    path('reject/<int:id>/', views.rejectAppointment, name='reject'),
    # path('MedicalTable/', views.MedicalTable, name='MedicalTable'),
    path('StaffDetails/', views.StaffDetails, name='StaffDetails'),
    path('doctor_allocated/', views.doctor_allocated_patients, name='doctor_allocated'),
    path('Doctor_Dashboard/', views.Dashboard_Doctor, name='Doctor_Dashboard'),
    path('CompletedReview/', views.CompleteReview, name='CompletedReview'),
    path('admin_dashboard/', views.AdminDashboard, name='admin_dashboard'),
    path('DoctorAssign/',views.DoctorAssignedPatients, name='DoctorAssign'),
    path('doctors_dashboard/', views.doctor_dashboard, name='doctors_dashboard'),
    path('doctor_database/', views.doctor_database, name='doctor_database'),
    path('doctor_auth/', views.DoctorAuth , name='doctor_auth'),
     path("doctor_home/", views.doctor_home, name="doctor_home"),
     path("doctor_patients/", views.doctor_patients, name="doctor_patients"),

    # path('approve_booking/<int:booking_id>/', views.approve_booking, name='approve_booking'),
    path('patientBookings/' ,views.PatientBookings, name='patientBookings'),
     path("admin_appointments/", views.admin_appointments, name="admin_appointments"),
      path("admin_appointments/approve/<int:booking_id>/", views.approve_appointment, name="approve_appointment"),
       path("admin_appointments/reject/<int:booking_id>/", views.reject_appointment, name="reject_appointment"),
]
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)